### PR TITLE
Prevent browser caching

### PR DESCRIPTION
**Pull request by andrejewski**
See #106. Trying to prevent browser caching. How to test this (other than the test can run all at once now)?

### CODE REVIEW

**Comment by matthewp** [comment]
👍

**Comment by phillipskevin** [comment]
@andrejewski do the tests fail if you remove the `nocache` function?

**Comment by andrejewski** [comment]
@phillipskevin I will try that. Right now I'm thinking I need to reorder the tests, in the build the Coverage tests run first which I don't think will error for the normal tests, I want to flip them around.

**Comment by phillipskevin** [comment]
Yeah, you can just rename the coverage test file to try it out.

**Comment by andrejewski** [comment]
@phillipskevin re-ordering the files still passes based on [the new build](https://travis-ci.org/bitovi/testee/builds/230866768?utm_source=github_status&utm_medium=notification).

**Pull request merged**
