### PR TITLE
Use native Promises, remove Q dependency

### LINKED ISSUE #122: use native Promises
fewer dependencies and better interoperability

### PR DESCRIPTION
**Pull request by andrejewski**
Fixes #122. This may break a few people so it'll have to be a part of v0.6.0. Overall, this is a great improvement over letting our Q dependency to leak out into other people's code. [Q's API is quite large](https://github.com/kriskowal/q/wiki/API-Reference) whereas Promises only have `then/catch`. The sooner this change is in, the sooner we can make stronger assumptions about our API contracts going forward.

### CODE REVIEW

**Comment by phillipskevin** [comment]
So this will break for people that (a) are trying to run tests using Promises in browsers that don't support Promises? And (b) people using parts of Q's API in their tests?

**Comment by andrejewski** [comment]
@phillipskevin This should not effect people running browser tests, `testee-client` would be responsible for those problems. If Q was being used in browsers we should work to remove that bloat too, in a separate issue. This **will break** people's tests which use the Q API directly, however that should be in almost all cases use of `.done()/.fail()` which are simple fixes to `.then()/.catch()`. This is why this needs to go into a minor release (0.6.0, 0.x changes I consider major) with good release notes.

**Comment by phillipskevin** [comment]
Ok, thanks for explaining.

**Comment by matthewp** [comment]
👍

**Pull request merged**
