### PR TITLE
fix XUnit reporter output. Closes #97

### LINKED ISSUE #97: Issue in XUnit reporter
There is a issue in Xunit reporter which is fixed with mocha 3.2.0
see 
https://github.com/mochajs/mocha/issues/2584

### PR DESCRIPTION
**Pull request by eintrachtfan**
see mocha issue https://github.com/mochajs/mocha/issues/2584

### CODE REVIEW

**Comment by daffl** [comment]
Due to the `^`, that version should be installed automatically if you reinstall with a clean npm cache.

**Comment by eintrachtfan** [comment]
@daffl I tried this but its still pulling  a mocha 2.5.3. 
Since testee doesn't work with that combinationaccordign to the doumentation here https://github.com/bitovi/testee#ci-integration, can't we not reference the higher version?

**Comment by daffl** [comment]
True. I always thought migrating to a higher version would require more effort since it is using some internals but it looks like the tests are passing.

**Comment by daffl** [comment]
Thank you! Released as 0.3.0 (final)

**Comment by eintrachtfan** [comment]
Thank you!

**Pull request merged**
