### PR TITLE
Convert test titles to strings

### LINKED ISSUE #136: Error thrown when test titles are non-strings
An error is thrown when `data.title` is a non-string here: [`new mocha.Test(data.title, true)`](https://github.com/bitovi/testee/blob/master/lib/reporter/index.js#L203).

```
(node:26651) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Test `title` should be a "string" but "number" was given instead.
(node:26651) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: No test information found for {"file":"http://localhost:3996/test/index.html","id":"3579e9fb15341a2bdf24b2bd7ee32d3b","title":5,"parent":"64b475e08b3b8c40f6040445dadc1695","status":"passed","state":"passed"}
```

This happens in situations like this:

```
QUnit.ok(m.l[0].id, 5, "correct props");
```

We should coerce these titles to strings.

### PR DESCRIPTION
**Pull request by andrejewski**
Fixes #136

### CODE REVIEW

**Comment by phillipskevin** [comment]
Thanks, @andrejewski! Can you add a test for this? Or is it not possible to catch the error that is thrown?

**Comment by andrejewski** [comment]
@phillipskevin It maybe be possible, I'd have to create a test file, run it with Testee, and see if the error is passed to `.fail`.

**Comment by phillipskevin** [comment]
It's worth trying if you have the time.

**Comment by andrejewski** [comment]
Closing as this is not something we should be fixing.

**Pull request closed without merging**
